In [85]:
import pandas as pd
from pyarrow import binary
from sqlalchemy import create_engine
import sqlalchemy as sa
import oracledb
from sqlalchemy.dialects.postgresql import psycopg_async, psycopg2
import psycopg
import sys
import psycopg2
import oracledb
import pyodbc
import urllib
from sqlalchemy import create_engine

# Create a DB Connectrion

In [24]:
# This is for the Retail_db Database
postgress1_tgt_conn = create_engine('postgresql+psycopg://retail_user:test@localhost:5432/retail_db')

## Connection for  Shop_db Database

In [86]:
# This is for the Shop_db Database
postgress1_tgt_conn = create_engine('postgresql+psycopg://shop_user:test@localhost:5432/shop_db')

In [110]:
postgress1_tgt_conn

Engine(postgresql+psycopg://shop_user:***@localhost:5432/shop_db)

In [111]:
df_target = pd.read_sql('select * from product', postgress1_tgt_conn)

In [112]:
df_target.head(5)

,product_id,product_name,category,price,quantity,supplier,product_status
0,1001,Laptop Pro 14,Electronics,74999.0,15,TechWorld,ACTIVE
1,1002,Wireless Mouse,Electronics,1299.0,80,TechWorld,ACTIVE
2,1003,Mechanical Keyboard,Electronics,3499.0,45,KeyMart,ACTIVE
3,1004,USB-C Hub,Accessories,1899.0,60,ConnectPlus,ACTIVE
4,1005,27 Inch Monitor,Electronics,21999.0,25,VisionTech,ACTIVE

In [18]:
#with oracledb.connect() as connection:
#postgres_src_conn = create_engine('postgresql://test:test@localhost:5432/postgres')
oracle_src_conn = create_engine('oracle+oracledb://repo:repo@localhost:1522/xe')

In [19]:
oracle_src_conn

Engine(oracle+oracledb://repo:***@localhost:1522/xe)

In [36]:
oracledb.init_oracle_client(lib_dir='C:\\Users\\USER\\Downloads\\instantclient-basic\\instantclient_23_26')
df_orcl_src = pd.read_sql('select * from product', oracle_src_conn)

In [37]:
df_orcl_src.head(5)

,product_id,product_name,category,price,quantity,supplier,product_status
0,1001,Laptop Pro 14,Electronics,74999.0,15,TechWorld,ACTIVE
1,1002,Wireless Mouse,Electronics,1299.0,80,TechWorld,ACTIVE
2,1003,Mechanical Keyboard,Electronics,3499.0,45,KeyMart,ACTIVE
3,1004,USB-C Hub,Accessories,1899.0,60,ConnectPlus,ACTIVE
4,1005,27 Inch Monitor,Electronics,21999.0,25,VisionTech,ACTIVE

In [90]:
fil = ~df_orcl_src['product_id'].isin(df_target['product_id'])

In [91]:
df_orcl_src[fil]

Empty DataFrame
Columns: [product_id, product_name, category, price, quantity, supplier, product_status]
Index: []

In [92]:
df_csv_src = pd.read_csv('data/product.csv')

In [93]:
df_csv_src.tail(5)

,product_id,product_name,category,price,quantity,supplier,product_status
17,1018,Standing Desk,Furniture,18999.0,8,OfficeGear,ACTIVE
18,1019,Laser Printer,Printers,12999.0,14,PrintTech,ACTIVE
19,1020,Inkjet Printer,Printers,7999.0,22,PrintTech,INACTIVE
20,1023,Inkjet Printer,Printers,7999.0,22,PrintTech,INACTIVE
21,1022,Inkjet Printer,Printers,7999.0,22,PrintTech,INACTIVE

In [94]:
df_csv_src['product_id'].tail(5)

17    1018
18    1019
19    1020
20    1023
21    1022
Name: product_id, dtype: int64

In [95]:
# we use tilde to change the true to false
fil_csv = ~df_csv_src['product_id'].isin(df_target['product_id'])

In [96]:
fil_csv

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20     True
21     True
Name: product_id, dtype: bool

### Check if Source is having more product_id's than the target

In [97]:
df_csv_src[fil_csv]

,product_id,product_name,category,price,quantity,supplier,product_status
20,1023,Inkjet Printer,Printers,7999.0,22,PrintTech,INACTIVE
21,1022,Inkjet Printer,Printers,7999.0,22,PrintTech,INACTIVE

### Check if Target is having more product_id's than the source

In [98]:
fil_csv1 = ~df_target['product_id'].isin(df_csv_src['product_id'])

In [99]:
df_target[fil_csv1]

,product_id,product_name,category,price,quantity,supplier,product_status
20,1021,Office Chair,Furniture,8999.0,12,OfficeGear,ACTIVE

### Check if Target is having more column than the source for all column

In [100]:
df_target.equals(df_csv_src)

False

In [ ]:
assert df_target.equals(df_csv_src), 'data between source and target not marching'

In [108]:
df_csv_src.tail(5)

,product_id,product_name,category,price,quantity,supplier,product_status
17,1018,Standing Desk,Furniture,18999.0,8,OfficeGear,ACTIVE
18,1019,Laser Printer,Printers,12999.0,14,PrintTech,ACTIVE
19,1020,Inkjet Printer,Printers,7999.0,22,PrintTech,INACTIVE
20,1023,Inkjet Printer,Printers,7999.0,22,PrintTech,INACTIVE
21,1022,Inkjet Printer,Printers,7999.0,22,PrintTech,INACTIVE

In [107]:
df_csv_src.dtypes

product_id          int64
product_name       object
category           object
price             float64
quantity            int64
supplier           object
product_status     object
dtype: object

In [106]:
df_target.dtypes

product_id          int64
product_name       object
category           object
price             float64
quantity            int64
supplier           object
product_status     object
dtype: object

In [113]:
df_target.tail(5)

,product_id,product_name,category,price,quantity,supplier,product_status
17,1018,Standing Desk,Furniture,18999.0,8,OfficeGear,ACTIVE
18,1019,Laser Printer,Printers,12999.0,14,PrintTech,ACTIVE
19,1020,Inkjet Printer,Printers,7999.0,22,PrintTech,INACTIVE
20,1022,Office Chair,Furniture,8999.0,12,OfficeGear,ACTIVE
21,1023,Inkjet Printer,Printers,7999.0,22,PrintTech,INACTIVE

In [114]:
df_target.compare(df_csv_src)

   product_id                         product_name  \
         self   other                         self
0         NaN     NaN                          NaN
7         NaN     NaN  Noise Cancelling Headphones
15        NaN     NaN             Wireless Charger
20     1022.0  1023.0                 Office Chair
21     1023.0  1022.0                          NaN

                                        category                price  \
                              other         self       other     self
0                               NaN  Electronics  Electronic  74999.0
7   Noisesksk Cancelling Headphones          NaN         NaN      NaN
15             Wireless Chargaaaaer          NaN         NaN      NaN
20                   Inkjet Printer    Furniture    Printers   8999.0
21                              NaN          NaN         NaN      NaN

            quantity          supplier             product_status
      other     self other        self       other           self     other
0   74988.0      NaN   NaN   TechWorld  TechWorld1            NaN       NaN
7       NaN      NaN   NaN         NaN         NaN            NaN       NaN
15      NaN      NaN   NaN         NaN         NaN            NaN       NaN
20   7999.0     12.0  22.0  OfficeGear   PrintTech         ACTIVE  INACTIVE
21      NaN      NaN   NaN         NaN         NaN            NaN       NaN

In [ ]:
df_target[fil_csv2]