In [10]:
import pandas as pd
from openpyxl.styles.builtins import title
from pandas.core.missing import check_value_size

In [11]:
df = pd.read_csv('emp.csv')

In [12]:
df.head()

   eno   ename  salary  deptno         doj
0   10   Amber    1000      10  2018-05-14
1    2    Amar    1000      10  2017-03-22
2    8   Sagar    1000      20  2020-11-30
3    4  Thomas    1000      10  2019-08-18
4    5    Jade    2000      10  2021-02-10

In [13]:
#specify which columns to read
df = pd.read_csv("emp.csv", usecols=["eno", "ename", "salary"])

In [14]:
df

    eno    ename  salary
0    10    Amber    1000
1     2     Amar    1000
2     8    Sagar    1000
3     4   Thomas    1000
4     5     Jade    2000
5     6    Smith    1000
6     7   Robert    3000
7     3     Nick    1000
8     9    Naman    4000
9     1    Vikas    1000
10   11   Dennis   41000
11   12    Karan    2200
12   13   Simran    1500
13   14     Amit    2000
14   15     Neha    1700
15   16    Rahul    1200
16   17    Divya    3000
17   18   Rakesh    1800
18   19   Monica    2500
19   20     John    2300
20   21    Sneha    2700
21   22    David    1000
22   23    Anita    1500
23   24    Vinod    1800
24   25    Meena    2000
25   26    Harsh    1600
26   27   Kavita    1400
27   28    Mohan    1300
28   29    Priya    1200
29   30   Suresh    1100
30   31     Rani    1900
31   32     Ajay    2100
32   33    Nidhi    2400
33   34    Vivek    2000
34   35    Seema    3000
35   36     Ritu    3200
36   37    Kunal    2800
37   38     Alok    2700
38   39   Poonam    2600
39   40     Yash    2500
40   41     Nina    2300
41   42    Tarun    2200
42   43    Geeta    2100
43   44    Ashok    1900
44   45  Sanjana    1800
45   46    Manoj    1700
46   47    Payal    1600

In [15]:
# specfying on ly on colunms
df["ename"]

0       Amber
1        Amar
2       Sagar
3      Thomas
4        Jade
5       Smith
6      Robert
7        Nick
8       Naman
9       Vikas
10     Dennis
11      Karan
12     Simran
13       Amit
14       Neha
15      Rahul
16      Divya
17     Rakesh
18     Monica
19       John
20      Sneha
21      David
22      Anita
23      Vinod
24      Meena
25      Harsh
26     Kavita
27      Mohan
28      Priya
29     Suresh
30       Rani
31       Ajay
32      Nidhi
33      Vivek
34      Seema
35       Ritu
36      Kunal
37       Alok
38     Poonam
39       Yash
40       Nina
41      Tarun
42      Geeta
43      Ashok
44    Sanjana
45      Manoj
46      Payal
Name: ename, dtype: object

In [16]:
# Specify a primary key (eno)
df = pd.read_csv("emp.csv", usecols=["eno", "ename", "salary"], index_col="eno")

In [17]:
df

       ename  salary
eno
10     Amber    1000
2       Amar    1000
8      Sagar    1000
4     Thomas    1000
5       Jade    2000
6      Smith    1000
7     Robert    3000
3       Nick    1000
9      Naman    4000
1      Vikas    1000
11    Dennis   41000
12     Karan    2200
13    Simran    1500
14      Amit    2000
15      Neha    1700
16     Rahul    1200
17     Divya    3000
18    Rakesh    1800
19    Monica    2500
20      John    2300
21     Sneha    2700
22     David    1000
23     Anita    1500
24     Vinod    1800
25     Meena    2000
26     Harsh    1600
27    Kavita    1400
28     Mohan    1300
29     Priya    1200
30    Suresh    1100
31      Rani    1900
32      Ajay    2100
33     Nidhi    2400
34     Vivek    2000
35     Seema    3000
36      Ritu    3200
37     Kunal    2800
38      Alok    2700
39    Poonam    2600
40      Yash    2500
41      Nina    2300
42     Tarun    2200
43     Geeta    2100
44     Ashok    1900
45   Sanjana    1800
46     Manoj    1700
47     Payal    1600

In [18]:
# Return record with eno = 8
df.iloc[8]

ename     Naman
salary     4000
Name: 9, dtype: object

In [19]:
# Return record with emp # 8 and 10
df.iloc[[8,10]]

      ename  salary
eno
9     Naman    4000
11   Dennis   41000

In [20]:
df.loc[[8,10]]

     ename  salary
eno
8    Sagar    1000
10   Amber    1000

In [21]:
df.head()

      ename  salary
eno
10    Amber    1000
2      Amar    1000
8     Sagar    1000
4    Thomas    1000
5      Jade    2000

In [22]:
df.loc[[2,8]]

     ename  salary
eno
2     Amar    1000
8    Sagar    1000

In [23]:
df.iloc[[2,8]]

     ename  salary
eno
8    Sagar    1000
9    Naman    4000

In [24]:
# Get specific colunms and rows
df[["salary","ename"]].iloc[[2,8]]

     salary  ename
eno
8      1000  Sagar
9      4000  Naman

In [25]:
# Get specific range of rows
df[["salary","ename"]].iloc[2:8]

     salary   ename
eno
8      1000   Sagar
4      1000  Thomas
5      2000    Jade
6      1000   Smith
7      3000  Robert
3      1000    Nick

In [26]:
# Return range of rows while jumping by 2 - it is like slicing
df[["salary","ename"]].iloc[2:8:2]

     salary   ename
eno
8      1000   Sagar
5      2000    Jade
7      3000  Robert

In [27]:
df.dtypes

ename     object
salary     int64
dtype: object

In [28]:
# Specify data types of the colunm
df= pd.read_csv("emp.csv",dtype={"salary":float})

In [29]:
df.head()

   eno   ename  salary  deptno         doj
0   10   Amber  1000.0      10  2018-05-14
1    2    Amar  1000.0      10  2017-03-22
2    8   Sagar  1000.0      20  2020-11-30
3    4  Thomas  1000.0      10  2019-08-18
4    5    Jade  2000.0      10  2021-02-10

In [30]:
df = pd.read_csv("netflix_dataset.csv")

In [31]:
df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [32]:
df.count()

show_id         8807
type            8807
title           8807
director        6173
cast            7982
country         7976
date_added      8797
release_year    8807
rating          8803
duration        8804
listed_in       8807
description     8807
dtype: int64

In [33]:
# Read teh dat in chunk (chunk size)
for chunk in pd.read_csv("netflix_dataset.csv",chunksize=1000):
    print(chunk.head())

  show_id     type                  title         director  \
0      s1    Movie   Dick Johnson Is Dead  Kirsten Johnson
1      s2  TV Show          Blood & Water              NaN
2      s3  TV Show              Ganglands  Julien Leclercq
3      s4  TV Show  Jailbirds New Orleans              NaN
4      s5  TV Show           Kota Factory              NaN

                                                cast        country  \
0                                                NaN  United States
1  Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...   South Africa
2  Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...            NaN
3                                                NaN            NaN
4  Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...          India

           date_added  release_year rating   duration  \
0  September 25, 2021          2020  PG-13     90 min
1  September 24, 2021          2021  TV-MA  2 Seasons
2  September 24, 2021          2021  TV-MA   1 Season
3  September 24, 2021          2021  TV-MA   1 Season
4  September 24, 2021          2021  TV-MA  2 Seasons

                                           listed_in  \
0                                      Documentaries
1    International TV Shows, TV Dramas, TV Mysteries
2  Crime TV Shows, International TV Shows, TV Act...
3                             Docuseries, Reality TV
4  International TV Shows, Romantic TV Shows, TV ...

                                         description
0  As her father nears the end of his life, filmm...
1  After crossing paths at a party, a Cape Town t...
2  To protect his family from a powerful drug lor...
3  Feuds, flirtations and toilet talk go down amo...
4  In a city of coaching centers known to train I...
     show_id     type               title         director  \
1000   s1001    Movie            Wild Dog  Ahishor Solomon
1001   s1002    Movie            Oloibiri    Curtis Graham
1002   s1003    Movie        Tell Me When   Gerardo Gatica
1003   s1004  TV Show                Zero              NaN
1004   s1005  TV Show  Izzy's Koala World              NaN

                                                   cast  \
1000  Nagarjuna Akkineni, Dia Mirza, Saiyami Kher, A...
1001  Olu Jacobs, Richard Mofe-Damijo, William R. Mo...
1002  Jesús Zavala, Ximena Romo, Verónica Castro, Jo...
1003  Giuseppe Dave Seke, Haroun Fall, Beatrice Gran...
1004                         Izzy Bee, Ali Bee, Tim Bee

                             country      date_added  release_year rating  \
1000                             NaN  April 22, 2021          2020  TV-MA
1001  Canada, Nigeria, United States  April 21, 2021          2015  TV-14
1002                          Mexico  April 21, 2021          2021  TV-MA
1003                           Italy  April 21, 2021          2021  TV-MA
1004                       Australia  April 20, 2021          2021   TV-Y

       duration                                       listed_in  \
1000    126 min        Action & Adventure, International Movies
1001     86 min         Dramas, International Movies, Thrillers
1002     97 min                  Comedies, International Movies
1003   1 Season  International TV Shows, TV Comedies, TV Dramas
1004  2 Seasons                                        Kids' TV

                                            description
1000  A brash but brilliant Indian intelligence agen...
1001  After drilling depletes a small village, a cor...
1002  Workaholic Will puts his humdrum life in LA on...
1003  A shy teen with the power to turn invisible mu...
1004  Young koala caretaker Izzy Bee and her family ...
     show_id     type                      title       director  \
2000   s2001    Movie  Michael McIntyre: Showman     Chris Howe
2001   s2002    Movie      Raising Victor Vargas  Peter Sollett
2002   s2003  TV Show            Taco Chronicles            NaN
2003   s2004    Movie               The Smurfs 2   Raja Gosnell
2004   s2005    Movie        Wish Upon a Unicorn  Steve Bencich

                                                   cast  \
2000                                   Michael McIntyre
2001  Victor Rasuk, Judy Marte, Melonie Diaz, Altagr...
2002                                                NaN
2003  Neil Patrick Harris, Brendan Gleeson, Jayma Ma...
2004  Ryan Kiera Armstrong, Summer Fontana, Kevin J....

                                     country          date_added  \
2000                          United Kingdom  September 15, 2020
2001                   France, United States  September 15, 2020
2002                           United States  September 15, 2020
2003  United States, France, Canada, Belgium  September 15, 2020
2004                                     NaN  September 15, 2020

      release_year rating   duration  \
2000          2020  TV-MA     63 min
2001          2002      R     88 min
2002          2020  TV-MA  2 Seasons
2003          2013     PG    105 min
2004          2020     PG     93 min

                                           listed_in  \
2000                                 Stand-Up Comedy
2001     Dramas, Independent Movies, Romantic Movies
2002  Docuseries, International TV Shows, Reality TV
2003              Children & Family Movies, Comedies
2004                        Children & Family Movies

                                            description
2000  Charming comic Michael McIntyre talks family, ...
2001  A suave teen sets his sights on a girl who see...
2002  Many of the most popular taco styles have long...
2003  Evil magician Gargamel continues his quest to ...
2004  Sisters Mia and Emma move to their grandmother...
     show_id     type                                 title  \
3000   s3001  TV Show  Pandemic: How to Prevent an Outbreak
3001   s3002  TV Show                     Playing with Fire
3002   s3003    Movie                                Whisky
3003   s3004    Movie       Fortune Feimster: Sweet & Salty
3004   s3005    Movie                   KD (A) Karuppudurai

                             director  \
3000                              NaN
3001                              NaN
3002  Pablo Stoll, Juan Pablo Rebella
3003                    Krysia Plonka
3004                        Madhumita

                                                   cast  \
3000                                                NaN
3001  Jason Day, Margarita Rosa de Francisco, Carlos...
3002  Andrés Pazos, Mirella Pascual, Jorge Bolani, J...
3003                                   Fortune Feimster
3004  Mu Ramaswamy, Naga Vishal, Yog Japee, Ganesan ...

                                 country        date_added  release_year  \
3000                       United States  January 22, 2020          2020
3001                       United States  January 22, 2020          2019
3002  Uruguay, Argentina, Germany, Spain  January 22, 2020          2004
3003                       United States  January 21, 2020          2020
3004                               India  January 21, 2020          2019

     rating  duration                                          listed_in  \
3000  TV-14  1 Season                    Docuseries, Science & Nature TV
3001  TV-MA  1 Season  International TV Shows, Romantic TV Shows, Spa...
3002  TV-MA    98 min             Comedies, Dramas, International Movies
3003  TV-MA    61 min                                    Stand-Up Comedy
3004  TV-14   116 min               Comedies, Dramas, Independent Movies

                                            description
3000  In this docuseries, meet the heroes on the fro...
3001  Three prosperous women – including a mother an...
3002  To impress family, a factory owner pretends to...
3003  Actor, comedian and writer Fortune Feimster ta...
3004  As his children plot his death to claim their ...
     show_id     type                         title            director  \
4000   s4001    Movie                  5 Flights Up   Richard Loncraine
4001   s4002  TV Show                    Green Door                 NaN
4002   s4003    Movie                    Bombairiya         Pia Sukanya
4003   s4004    Movie                      Burn Out         Yann Gozlan
4004   s4005    Movie  Edoardo Ferrario: Temi Caldi  Francesco Imperato

                                                   cast  \
4000  Josh Pais, Claire van der Boom, Morgan Freeman...
4001  Jam Hsiao, Bea Hayden Kuo, Enno Cheng, Hsieh Y...
4002  Radhika Apte, Siddhant Kapoor, Akshay Oberoi, ...
4003  Olivier Rabourdin, François Civil, Manon Azem,...
4004                                   Edoardo Ferrario

                                          country      date_added  \
4000                                United States  March 17, 2019
4001                                       Taiwan  March 17, 2019
4002  United Arab Emirates, United Kingdom, India  March 15, 2019
4003                              France, Belgium  March 15, 2019
4004                                        Italy  March 15, 2019

      release_year rating  duration  \
4000          2014  PG-13    92 min
4001          2019  TV-MA  1 Season
4002          2018  TV-MA   108 min
4003          2017  TV-MA   104 min
4004          2019  TV-MA    65 min

                                              listed_in  \
4000               Comedies, Dramas, Independent Movies
4001  International TV Shows, Romantic TV Shows, TV ...
4002             Comedies, Dramas, International Movies
4003           Action & Adventure, International Movies
4004                                    Stand-Up Comedy

                                            description
4000  A couple finds unexpected drama when, after 40...
4001  A troubled psychologist returns from the U.S. ...
4002  A PR agent trying to find her stolen phone, a ...
4003  When his son's mom runs afoul of Paris's crimi...
4004  Italian comedian Edoardo Ferrario riffs on lif...
     show_id     type                              title  \
5000   s5001  TV Show                         Flint Town
5001   s5002    Movie  Malena Pichot: Estupidez compleja
5002   s5003    Movie   Natalia Valdebenito: El especial
5003   s5004    Movie                           Ravenous
5004   s5005  TV Show                         21 Thunder

                    director  \
5000                     NaN
5001  Raúl Campos, Jan Suter
5002  Raúl Campos, Jan Suter
5003            Robin Aubert
5004                     NaN

                                                   cast        country  \
5000                                                NaN  United States
5001                                      Malena Pichot      Argentina
5002                                Natalia Valdebenito          Chile
5003  Marc-André Grondin, Monia Chokri, Charlotte St...         Canada
5004  Stephanie Bennett, Emmanuel Kabongo, RJ Fether...         Canada

         date_added  release_year rating  duration  \
5000  March 2, 2018          2018  TV-MA  1 Season
5001  March 2, 2018          2018  TV-MA    51 min
5002  March 2, 2018          2018  TV-MA    69 min
5003  March 2, 2018          2017  TV-MA   104 min
5004  March 1, 2018          2017  TV-MA  1 Season

                                              listed_in  \
5000                    Docuseries, Science & Nature TV
5001                                    Stand-Up Comedy
5002                                    Stand-Up Comedy
5003                Horror Movies, International Movies
5004  Crime TV Shows, International TV Shows, TV Dramas

                                            description
5000  Over a two-year period, filmmakers embedded wi...
5001  An Argentine comedian espouses the values of f...
5002  A Chilean comedian fuses activism with irrever...
5003  As a zombie plague ravages their rural Quebec ...
5004  Players and coaches for a Montreal soccer team...
     show_id     type                         title                director  \
6000   s6001    Movie                     21 & Over  Jon Lucas, Scott Moore
6001   s6002  TV Show  21 Sarfarosh: Saragarhi 1897                     NaN
6002   s6003    Movie          2307: Winter's Dream             Joey Curtis
6003   s6004    Movie              24 Hours to Live              Brian Smrz
6004   s6005    Movie   27, el club de los malditos          Nicanor Loreti

                                                   cast  \
6000  Miles Teller, Skylar Astin, Justin Chon, Sarah...
6001                 Luke Kenny, Mohit Raina, Mukul Dev
6002  Paul Sidhu, Arielle Holmes, Branden Coles, Kel...
6003  Ethan Hawke, Xu Qing, Paul Anderson, Rutger Ha...
6004  Diego Capusotto, Sofía Gala, Daniel Aráoz, Wil...

                                 country        date_added  release_year  \
6000                       United States    April 16, 2019          2013
6001                               India  December 1, 2018          2018
6002                       United States     March 1, 2018          2016
6003  South Africa, China, United States     April 7, 2018          2017
6004                           Argentina       May 1, 2018          2018

     rating  duration                                          listed_in  \
6000      R    93 min                                           Comedies
6001  TV-14  1 Season                  International TV Shows, TV Dramas
6002  TV-MA   101 min  Action & Adventure, Independent Movies, Sci-Fi...
6003      R    93 min                                 Action & Adventure
6004  TV-MA    82 min  Action & Adventure, Comedies, International Mo...

                                            description
6000  Jeff's straight-and-narrow life changes abrupt...
6001  In one of history's greatest last stands, a ba...
6002  In the frozen tundra of a futuristic Arizona w...
6003  Revived by an experimental procedure, a hit ma...
6004  After a musician dies under suspicious circums...
     show_id   type                 title        director  \
7000   s7001  Movie  Hostage to the Devil   Marty Stalker
7001   s7002  Movie              Hostages  Federico Lemos
7002   s7003  Movie              Hostiles    Scott Cooper
7003   s7004  Movie               Hot Bot  Michael Polish
7004   s7005  Movie          Hot Property      Max McGill

                                                   cast  \
7000                                                NaN
7001                                                NaN
7002  Christian Bale, Rosamund Pike, Wes Studi, Jess...
7003  Cynthia Kirchner, Doug Haley, Zack Pearlman, L...
7004  MyAnna Buring, Tom Rhys Harries, Ella Smith, S...

                                            country        date_added  \
7000  Ireland, United Kingdom, Italy, United States  January 15, 2017
7001                                            NaN  January 29, 2018
7002                                  United States   August 15, 2018
7003                                  United States     March 1, 2016
7004                                 United Kingdom   August 13, 2017

      release_year rating duration                            listed_in  \
7000          2016  TV-14   96 min  Documentaries, International Movies
7001          2017  TV-PG   91 min  Documentaries, International Movies
7002          2017      R  134 min                               Dramas
7003          2016     NR   93 min                             Comedies
7004          2016  TV-MA   82 min         Comedies, Independent Movies

                                            description
7000  Follow the eerie story of Father Malachi Marti...
7001  Witnesses recount the shocking 1996 hostage cr...
7002  After a long career battling the Cheyenne, a U...
7003  Two teenage geeks inadvertently find a lifelik...
7004  When a resourceful but flighty Londoner is thr...
     show_id     type            title                   director  \
8000   s8001    Movie     She Did That                        NaN
8001   s8002    Movie          Shelter  Måns Mårlind, Björn Stein
8002   s8003  TV Show         Sherlock                        NaN
8003   s8004    Movie  Sherlock Holmes                Guy Ritchie
8004   s8005    Movie            Shiva            Ram Gopal Varma

                                                   cast  \
8000  Luvvie Ajayi, Renae Bluitt, Melissa Butler, Li...
8001  Julianne Moore, Jonathan Rhys Meyers, Jeffrey ...
8002  Benedict Cumberbatch, Martin Freeman, Una Stub...
8003  Robert Downey Jr., Jude Law, Rachel McAdams, M...
8004  Nagarjuna Akkineni, Amala, Rajendranath Zutshi...

                                                country         date_added  \
8000                                      United States   February 4, 2020
8001                                      United States  December 29, 2017
8002                      United Kingdom, United States       May 15, 2017
8003  United States, Germany, United Kingdom, Australia    January 1, 2021
8004                                              India  December 31, 2019

      release_year rating   duration  \
8000          2019  TV-PG     71 min
8001          2010      R    112 min
8002          2017  TV-14  4 Seasons
8003          2009  PG-13    128 min
8004          1990  TV-MA    168 min

                                              listed_in  \
8000                                      Documentaries
8001                           Horror Movies, Thrillers
8002  British TV Shows, Crime TV Shows, Internationa...
8003                       Action & Adventure, Comedies
8004   Action & Adventure, Dramas, International Movies

                                            description
8000  Go inside the lives of extraordinary, black fe...
8001  A forensic psychiatrist has to think outside t...
8002  In this updated take on Sir Arthur Conan Doyle...
8003  The game is afoot for an eccentric detective w...
8004  A young man enrolls at a college and becomes a...

In [34]:
# show few colunms
for chunk in pd.read_csv("netflix_dataset.csv",usecols=["show_id","title"],chunksize=1000):
    print(chunk.head(10))

  show_id                             title
0      s1              Dick Johnson Is Dead
1      s2                     Blood & Water
2      s3                         Ganglands
3      s4             Jailbirds New Orleans
4      s5                      Kota Factory
5      s6                     Midnight Mass
6      s7  My Little Pony: A New Generation
7      s8                           Sankofa
8      s9     The Great British Baking Show
9     s10                      The Starling
     show_id                               title
1000   s1001                            Wild Dog
1001   s1002                            Oloibiri
1002   s1003                        Tell Me When
1003   s1004                                Zero
1004   s1005                  Izzy's Koala World
1005   s1006  Keymon and Nani in Space Adventure
1006   s1007            Motu Patlu Dino Invasion
1007   s1008         Motu Patlu in Octupus World
1008   s1009             Motu Patlu VS Robo Kids
1009   s1010     Rudra: Secret of the Black Moon
     show_id                      title
2000   s2001  Michael McIntyre: Showman
2001   s2002      Raising Victor Vargas
2002   s2003            Taco Chronicles
2003   s2004               The Smurfs 2
2004   s2005        Wish Upon a Unicorn
2005   s2006          Lara and the Beat
2006   s2007                      Buddi
2007   s2008                 Dad Wanted
2008   s2009            Family Business
2009   s2010                Girlfriends
     show_id                                        title
3000   s3001         Pandemic: How to Prevent an Outbreak
3001   s3002                            Playing with Fire
3002   s3003                                       Whisky
3003   s3004              Fortune Feimster: Sweet & Salty
3004   s3005                          KD (A) Karuppudurai
3005   s3006  DreamWorks How to Train Your Dragon Legends
3006   s3007                        Motichoor Chaknachoor
3007   s3008                            WHAT DID JACK DO?
3008   s3009                               The Bling Ring
3009   s3010                            A Fall from Grace
     show_id                              title
4000   s4001                       5 Flights Up
4001   s4002                         Green Door
4002   s4003                         Bombairiya
4003   s4004                           Burn Out
4004   s4005       Edoardo Ferrario: Temi Caldi
4005   s4006                               Girl
4006   s4007                If I Hadn't Met You
4007   s4008   Jeff Dunham: Arguing with Myself
4008   s4009      Jeff Dunham: Controlled Chaos
4009   s4010  Jeff Dunham: Minding the Monsters
     show_id                              title
5000   s5001                         Flint Town
5001   s5002  Malena Pichot: Estupidez compleja
5002   s5003   Natalia Valdebenito: El especial
5003   s5004                           Ravenous
5004   s5005                         21 Thunder
5005   s5006       Adel Karam: Live from Beirut
5006   s5007                       Battle Drone
5007   s5008                             Dil Se
5008   s5009                               Guru
5009   s5010                           Judwaa 2
     show_id                         title
6000   s6001                     21 & Over
6001   s6002  21 Sarfarosh: Saragarhi 1897
6002   s6003          2307: Winter's Dream
6003   s6004              24 Hours to Live
6004   s6005   27, el club de los malditos
6005   s6006             27: Gone Too Soon
6006   s6007                       28 Days
6007   s6008                   3 Deewarein
6008   s6009                 3 Generations
6009   s6010                    3 Heroines
     show_id                                  title
7000   s7001                   Hostage to the Devil
7001   s7002                               Hostages
7002   s7003                               Hostiles
7003   s7004                                Hot Bot
7004   s7005                           Hot Property
7005   s7006                                Hot Rod
7006   s7007                      Hotel Beau Séjour
7007   s7008                          Hotel Pacific
7008   s7009  Hotel Transylvania 3: Summer Vacation
7009   s7010         House at the End of the Street
     show_id                     title
8000   s8001              She Did That
8001   s8002                   Shelter
8002   s8003                  Sherlock
8003   s8004           Sherlock Holmes
8004   s8005                     Shiva
8005   s8006       Shopkins: Chef Club
8006   s8007            Shopkins: Wild
8007   s8008  Shopkins: World Vacation
8008   s8009                   Shorgul
8009   s8010             Short Term 12

In [35]:
#Using iterator
iterator =  pd.read_csv("netflix_dataset.csv",usecols=["show_id","title"],chunksize=1000,iterator=True)
for chunk in iterator:
    print(chunk.head(10))

  show_id                             title
0      s1              Dick Johnson Is Dead
1      s2                     Blood & Water
2      s3                         Ganglands
3      s4             Jailbirds New Orleans
4      s5                      Kota Factory
5      s6                     Midnight Mass
6      s7  My Little Pony: A New Generation
7      s8                           Sankofa
8      s9     The Great British Baking Show
9     s10                      The Starling
     show_id                               title
1000   s1001                            Wild Dog
1001   s1002                            Oloibiri
1002   s1003                        Tell Me When
1003   s1004                                Zero
1004   s1005                  Izzy's Koala World
1005   s1006  Keymon and Nani in Space Adventure
1006   s1007            Motu Patlu Dino Invasion
1007   s1008         Motu Patlu in Octupus World
1008   s1009             Motu Patlu VS Robo Kids
1009   s1010     Rudra: Secret of the Black Moon
     show_id                      title
2000   s2001  Michael McIntyre: Showman
2001   s2002      Raising Victor Vargas
2002   s2003            Taco Chronicles
2003   s2004               The Smurfs 2
2004   s2005        Wish Upon a Unicorn
2005   s2006          Lara and the Beat
2006   s2007                      Buddi
2007   s2008                 Dad Wanted
2008   s2009            Family Business
2009   s2010                Girlfriends
     show_id                                        title
3000   s3001         Pandemic: How to Prevent an Outbreak
3001   s3002                            Playing with Fire
3002   s3003                                       Whisky
3003   s3004              Fortune Feimster: Sweet & Salty
3004   s3005                          KD (A) Karuppudurai
3005   s3006  DreamWorks How to Train Your Dragon Legends
3006   s3007                        Motichoor Chaknachoor
3007   s3008                            WHAT DID JACK DO?
3008   s3009                               The Bling Ring
3009   s3010                            A Fall from Grace
     show_id                              title
4000   s4001                       5 Flights Up
4001   s4002                         Green Door
4002   s4003                         Bombairiya
4003   s4004                           Burn Out
4004   s4005       Edoardo Ferrario: Temi Caldi
4005   s4006                               Girl
4006   s4007                If I Hadn't Met You
4007   s4008   Jeff Dunham: Arguing with Myself
4008   s4009      Jeff Dunham: Controlled Chaos
4009   s4010  Jeff Dunham: Minding the Monsters
     show_id                              title
5000   s5001                         Flint Town
5001   s5002  Malena Pichot: Estupidez compleja
5002   s5003   Natalia Valdebenito: El especial
5003   s5004                           Ravenous
5004   s5005                         21 Thunder
5005   s5006       Adel Karam: Live from Beirut
5006   s5007                       Battle Drone
5007   s5008                             Dil Se
5008   s5009                               Guru
5009   s5010                           Judwaa 2
     show_id                         title
6000   s6001                     21 & Over
6001   s6002  21 Sarfarosh: Saragarhi 1897
6002   s6003          2307: Winter's Dream
6003   s6004              24 Hours to Live
6004   s6005   27, el club de los malditos
6005   s6006             27: Gone Too Soon
6006   s6007                       28 Days
6007   s6008                   3 Deewarein
6008   s6009                 3 Generations
6009   s6010                    3 Heroines
     show_id                                  title
7000   s7001                   Hostage to the Devil
7001   s7002                               Hostages
7002   s7003                               Hostiles
7003   s7004                                Hot Bot
7004   s7005                           Hot Property
7005   s7006                                Hot Rod
7006   s7007                      Hotel Beau Séjour
7007   s7008                          Hotel Pacific
7008   s7009  Hotel Transylvania 3: Summer Vacation
7009   s7010         House at the End of the Street
     show_id                     title
8000   s8001              She Did That
8001   s8002                   Shelter
8002   s8003                  Sherlock
8003   s8004           Sherlock Holmes
8004   s8005                     Shiva
8005   s8006       Shopkins: Chef Club
8006   s8007            Shopkins: Wild
8007   s8008  Shopkins: World Vacation
8008   s8009                   Shorgul
8009   s8010             Short Term 12

In [36]:
df = pd.read_csv('emp.csv')

In [37]:
df.head(20)

    eno   ename  salary  deptno         doj
0    10   Amber    1000      10  2018-05-14
1     2    Amar    1000      10  2017-03-22
2     8   Sagar    1000      20  2020-11-30
3     4  Thomas    1000      10  2019-08-18
4     5    Jade    2000      10  2021-02-10
5     6   Smith    1000      10  2016-12-01
6     7  Robert    3000      20  2023-06-25
7     3    Nick    1000      30  2015-09-15
8     9   Naman    4000      30  2020-01-20
9     1   Vikas    1000      30  2017-10-03
10   11  Dennis   41000      30  2024-01-05
11   12   Karan    2200      20  2018-06-16
12   13  Simran    1500      10  2019-12-19
13   14    Amit    2000      30  2022-04-09
14   15    Neha    1700      20  2021-07-22
15   16   Rahul    1200      10  2016-03-28
16   17   Divya    3000      30  2015-11-11
17   18  Rakesh    1800      10  2020-09-04
18   19  Monica    2500      20  2023-08-07
19   20    John    2300      30  2018-10-29

In [38]:
# use iloc t read the data from row 10 to row 20
# way 1
df.iloc[9:20]

    eno   ename  salary  deptno         doj
9     1   Vikas    1000      30  2017-10-03
10   11  Dennis   41000      30  2024-01-05
11   12   Karan    2200      20  2018-06-16
12   13  Simran    1500      10  2019-12-19
13   14    Amit    2000      30  2022-04-09
14   15    Neha    1700      20  2021-07-22
15   16   Rahul    1200      10  2016-03-28
16   17   Divya    3000      30  2015-11-11
17   18  Rakesh    1800      10  2020-09-04
18   19  Monica    2500      20  2023-08-07
19   20    John    2300      30  2018-10-29

In [39]:
# way 2 - Create a datafrae with rows 10 to 21
df = pd.read_csv("emp.csv",skiprows=10,nrows=11,header=None)

In [40]:
df

     0       1      2   3           4
0    1   Vikas   1000  30  2017-10-03
1   11  Dennis  41000  30  2024-01-05
2   12   Karan   2200  20  2018-06-16
3   13  Simran   1500  10  2019-12-19
4   14    Amit   2000  30  2022-04-09
5   15    Neha   1700  20  2021-07-22
6   16   Rahul   1200  10  2016-03-28
7   17   Divya   3000  30  2015-11-11
8   18  Rakesh   1800  10  2020-09-04
9   19  Monica   2500  20  2023-08-07
10  20    John   2300  30  2018-10-29

In [41]:
# Create a dataframe with names
df = pd.read_csv("emp.csv",skiprows=10,nrows=11,names=['empid','ename','sal','deptno','hiringdate'])

In [42]:
df

    empid   ename    sal  deptno  hiringdate
0       1   Vikas   1000      30  2017-10-03
1      11  Dennis  41000      30  2024-01-05
2      12   Karan   2200      20  2018-06-16
3      13  Simran   1500      10  2019-12-19
4      14    Amit   2000      30  2022-04-09
5      15    Neha   1700      20  2021-07-22
6      16   Rahul   1200      10  2016-03-28
7      17   Divya   3000      30  2015-11-11
8      18  Rakesh   1800      10  2020-09-04
9      19  Monica   2500      20  2023-08-07
10     20    John   2300      30  2018-10-29

In [43]:
# It is not considering any header
df = pd.read_csv('emp.csv',header=0)

In [44]:
df

    eno    ename  salary  deptno         doj
0    10    Amber    1000      10  2018-05-14
1     2     Amar    1000      10  2017-03-22
2     8    Sagar    1000      20  2020-11-30
3     4   Thomas    1000      10  2019-08-18
4     5     Jade    2000      10  2021-02-10
5     6    Smith    1000      10  2016-12-01
6     7   Robert    3000      20  2023-06-25
7     3     Nick    1000      30  2015-09-15
8     9    Naman    4000      30  2020-01-20
9     1    Vikas    1000      30  2017-10-03
10   11   Dennis   41000      30  2024-01-05
11   12    Karan    2200      20  2018-06-16
12   13   Simran    1500      10  2019-12-19
13   14     Amit    2000      30  2022-04-09
14   15     Neha    1700      20  2021-07-22
15   16    Rahul    1200      10  2016-03-28
16   17    Divya    3000      30  2015-11-11
17   18   Rakesh    1800      10  2020-09-04
18   19   Monica    2500      20  2023-08-07
19   20     John    2300      30  2018-10-29
20   21    Sneha    2700      10  2022-12-14
21   22    David    1000      20  2017-02-17
22   23    Anita    1500      30  2019-05-21
23   24    Vinod    1800      10  2016-07-30
24   25    Meena    2000      20  2020-03-13
25   26    Harsh    1600      10  2021-09-25
26   27   Kavita    1400      30  2019-01-06
27   28    Mohan    1300      10  2015-04-17
28   29    Priya    1200      20  2023-02-11
29   30   Suresh    1100      10  2018-09-09
30   31     Rani    1900      20  2022-11-03
31   32     Ajay    2100      10  2020-06-26
32   33    Nidhi    2400      30  2016-05-12
33   34    Vivek    2000      20  2017-07-31
34   35    Seema    3000      10  2021-10-15
35   36     Ritu    3200      20  2023-05-01
36   37    Kunal    2800      30  2015-08-22
37   38     Alok    2700      10  2019-03-02
38   39   Poonam    2600      20  2022-02-05
39   40     Yash    2500      30  2020-07-19
40   41     Nina    2300      20  2018-12-28
41   42    Tarun    2200      10  2021-01-09
42   43    Geeta    2100      30  2017-11-14
43   44    Ashok    1900      10  2016-06-08
44   45  Sanjana    1800      20  2023-03-17
45   46    Manoj    1700      30  2019-07-24
46   47    Payal    1600      20  2015-10-10

In [45]:
# using second  row a header
df = pd.read_csv('emp.csv',header=1)
df

    10    Amber   1000  10.1  2018-05-14
0    2     Amar   1000    10  2017-03-22
1    8    Sagar   1000    20  2020-11-30
2    4   Thomas   1000    10  2019-08-18
3    5     Jade   2000    10  2021-02-10
4    6    Smith   1000    10  2016-12-01
5    7   Robert   3000    20  2023-06-25
6    3     Nick   1000    30  2015-09-15
7    9    Naman   4000    30  2020-01-20
8    1    Vikas   1000    30  2017-10-03
9   11   Dennis  41000    30  2024-01-05
10  12    Karan   2200    20  2018-06-16
11  13   Simran   1500    10  2019-12-19
12  14     Amit   2000    30  2022-04-09
13  15     Neha   1700    20  2021-07-22
14  16    Rahul   1200    10  2016-03-28
15  17    Divya   3000    30  2015-11-11
16  18   Rakesh   1800    10  2020-09-04
17  19   Monica   2500    20  2023-08-07
18  20     John   2300    30  2018-10-29
19  21    Sneha   2700    10  2022-12-14
20  22    David   1000    20  2017-02-17
21  23    Anita   1500    30  2019-05-21
22  24    Vinod   1800    10  2016-07-30
23  25    Meena   2000    20  2020-03-13
24  26    Harsh   1600    10  2021-09-25
25  27   Kavita   1400    30  2019-01-06
26  28    Mohan   1300    10  2015-04-17
27  29    Priya   1200    20  2023-02-11
28  30   Suresh   1100    10  2018-09-09
29  31     Rani   1900    20  2022-11-03
30  32     Ajay   2100    10  2020-06-26
31  33    Nidhi   2400    30  2016-05-12
32  34    Vivek   2000    20  2017-07-31
33  35    Seema   3000    10  2021-10-15
34  36     Ritu   3200    20  2023-05-01
35  37    Kunal   2800    30  2015-08-22
36  38     Alok   2700    10  2019-03-02
37  39   Poonam   2600    20  2022-02-05
38  40     Yash   2500    30  2020-07-19
39  41     Nina   2300    20  2018-12-28
40  42    Tarun   2200    10  2021-01-09
41  43    Geeta   2100    30  2017-11-14
42  44    Ashok   1900    10  2016-06-08
43  45  Sanjana   1800    20  2023-03-17
44  46    Manoj   1700    30  2019-07-24
45  47    Payal   1600    20  2015-10-10

In [46]:
# starting from the fourth row
df = pd.read_csv('emp.csv',header=4)
df.head()

   4  Thomas  1000  10  2019-08-18
0  5    Jade  2000  10  2021-02-10
1  6   Smith  1000  10  2016-12-01
2  7  Robert  3000  20  2023-06-25
3  3    Nick  1000  30  2015-09-15
4  9   Naman  4000  30  2020-01-20

In [47]:
# Check data type
df = pd.read_csv('emp.csv')
df.dtypes

eno        int64
ename     object
salary     int64
deptno     int64
doj       object
dtype: object

In [48]:
#the the dtype of date to date_time
df = pd.read_csv('emp.csv',parse_dates=['doj'])
df.dtypes

eno                int64
ename             object
salary             int64
deptno             int64
doj       datetime64[ns]
dtype: object

In [49]:
df['doj'].head()

0   2018-05-14
1   2017-03-22
2   2020-11-30
3   2019-08-18
4   2021-02-10
Name: doj, dtype: datetime64[ns]

In [50]:
df['doj'].dt.year.head()

0    2018
1    2017
2    2020
3    2019
4    2021
Name: doj, dtype: int32

In [51]:
df['doj'].dt.month.head()

0     5
1     3
2    11
3     8
4     2
Name: doj, dtype: int32

In [52]:
df['doj'].dt.day.head()

0    14
1    22
2    30
3    18
4    10
Name: doj, dtype: int32

In [60]:
# Filtering (using where clause in SQL)
# get all emplyee that belong to dept 10 and 20 where salary >3000
df = pd.read_csv('emp.csv')
filter1 = df['deptno']==30
filter2 = df['salary']>3000

In [61]:
df[filter1&filter2]

    eno   ename  salary  deptno         doj
8     9   Naman    4000      30  2020-01-20
10   11  Dennis   41000      30  2024-01-05

In [62]:
# Sorting - we can sort by index or sort by value
df.sort_values(by='salary',ascending=False).head()

    eno   ename  salary  deptno         doj
10   11  Dennis   41000      30  2024-01-05
8     9   Naman    4000      30  2020-01-20
35   36    Ritu    3200      20  2023-05-01
16   17   Divya    3000      30  2015-11-11
34   35   Seema    3000      10  2021-10-15

In [66]:
df.sort_values(by=['deptno','salary'],ascending=False).head()

    eno   ename  salary  deptno         doj
10   11  Dennis   41000      30  2024-01-05
8     9   Naman    4000      30  2020-01-20
16   17   Divya    3000      30  2015-11-11
36   37   Kunal    2800      30  2015-08-22
39   40    Yash    2500      30  2020-07-19