In [2]:
import pandas as pd

Display First 5 data

In [138]:
df = pd.read_csv("emp.csv")
df.head()

   eno   ename  salary  deptno         doj    Location
0   10   Amber    1000      10  14/05/2018      Mumbai
1    2    Amar    1000      10  22/03/2017   Bangalore
2    8   Sagar    1000      20  30/11/2020  California
3    4  Thomas    1000      10  18/08/2019  California
4    5    Jade    2000      10  10/02/2021      London

Group By - Using aggregate functions (sum, min,max, count,avg)

In [96]:
# Using aggregate functions (sum, min,max, count,avg)
# Count the employees in each department
# Output should be the deptno, count_employees - expected output
# SQL - select deptno, count(*) from emp(df) group by deptno

df.groupby('deptno')['deptno'].count()

deptno
10    18
20    15
30    14
Name: deptno, dtype: int64

In [97]:
aggr_data = df.groupby('deptno')['eno'].count()
type(aggr_data)

pandas.core.series.Series

In [98]:
# convert the Series to Dataframe
aggr_data = aggr_data.reset_index()

In [99]:
aggr_data

   deptno  eno
0      10   18
1      20   15
2      30   14

In [100]:
type(aggr_data)

pandas.core.frame.DataFrame

In [102]:
# rename eno colunm to count_employees
aggr_data.rename(columns={'eno':'count_employees'}, inplace=True)

In [103]:
aggr_data

   deptno  count_employees
0      10               18
1      20               15
2      30               14

In [104]:
# get total count of employee, max salary, min salary, total salary in each department
# SQL: select count(eno) as employees_count, max(salary) as min_salary, sum (salar) as total_salary group by deptno

df.groupby('deptno')['salary'].count()

deptno
10    18
20    15
30    14
Name: salary, dtype: int64

In [165]:
df.groupby('eno')['salary'].count().reset_index()

    eno  salary
0     1       1
1     2       1
2     3       1
3     4       1
4     5       1
5     6       1
6     7       1
7     8       1
8     9       1
9    10       1
10   11       1
11   12       1
12   13       1
13   14       1
14   15       1
15   16       1
16   17       1
17   18       1
18   19       1
19   20       1
20   21       1
21   22       1
22   23       1
23   24       1
24   25       1
25   26       1
26   27       1
27   28       1
28   29       1
29   30       1
30   31       1
31   32       1
32   33       1
33   34       1
34   35       1
35   36       1
36   37       1
37   38       1
38   39       1
39   40       1
40   41       1
41   42       1
42   43       1
43   44       1
44   45       1
45   46       1
46   47       1

In [105]:
agg_data = df.groupby('deptno')['salary'].agg(['count','max','min','sum'])

In [106]:
agg_data
 #deptno behaves like index colunm

        count    max   min    sum
deptno
10         18   3000  1000  30900
20         15   3200  1000  30000
30         14  41000  1000  68700

In [107]:
type(agg_data)

pandas.core.frame.DataFrame

In [24]:
# to reset index
agg_data = agg_data.reset_index()

In [108]:
agg_data

        count    max   min    sum
deptno
10         18   3000  1000  30900
20         15   3200  1000  30000
30         14  41000  1000  68700

In [92]:
# t rename colunm
agg_data.rename(columns={'salary':'count_employees','count':'employee_count','max':'max_salary','min':'min_salary','sum':'total_salary'}, inplace=True)

In [109]:
agg_data

        count    max   min    sum
deptno
10         18   3000  1000  30900
20         15   3200  1000  30000
30         14  41000  1000  68700

In [110]:
agg_data.to_csv('emp_summary.csv',index=False)

In [111]:
df.head()

   eno   ename  salary  deptno         doj    Location
0   10   Amber    1000      10  14/05/2018   Bangalore
1    2    Amar    1000      10  22/03/2017   Bangalore
2    8   Sagar    1000      20  30/11/2020  California
3    4  Thomas    1000      10  18/08/2019  California
4    5    Jade    2000      10  10/02/2021      London

In [130]:
# Get employees count in each location within eac deptno
# expected output:
# SQL equivalent: select location, deptno,count(eno) as emp_count from emp group by location, deptno

data = df.groupby(['Location','deptno'])['eno'].count().reset_index()
data.rename(columns={'eno': 'employee_count'}, inplace=True)
data

         Location  deptno  employee_count
0           Abuja      30               1
1       Bangalore      10               2
2      California      10               1
3      California      20               1
4           Lagos      20               1
5           Lagos      30               1
6          London      10               6
7          London      20               5
8          London      30               3
9          Mumbai      10               5
10         Mumbai      20               4
11         Mumbai      30               3
12          Paris      20               1
13          Paris      30               1
14  Port Harcourt      30               1

In [131]:
data

         Location  deptno  employee_count
0           Abuja      30               1
1       Bangalore      10               2
2      California      10               1
3      California      20               1
4           Lagos      20               1
5           Lagos      30               1
6          London      10               6
7          London      20               5
8          London      30               3
9          Mumbai      10               5
10         Mumbai      20               4
11         Mumbai      30               3
12          Paris      20               1
13          Paris      30               1
14  Port Harcourt      30               1

In [139]:
df.head()

   eno   ename  salary  deptno         doj    Location
0   10   Amber    1000      10  14/05/2018      Mumbai
1    2    Amar    1000      10  22/03/2017   Bangalore
2    8   Sagar    1000      20  30/11/2020  California
3    4  Thomas    1000      10  18/08/2019  California
4    5    Jade    2000      10  10/02/2021      London

Get total salary in each department except for location = Mumbai

In [141]:
loc_filter = df['Location'] !='Mumbai'
loc_filter

0     False
1      True
2      True
3      True
4      True
5      True
6      True
7      True
8      True
9      True
10     True
11     True
12     True
13     True
14     True
15     True
16     True
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29     True
30     True
31     True
32     True
33     True
34     True
35     True
36     True
37     True
38     True
39     True
40     True
41     True
42     True
43     True
44     True
45     True
46     True
Name: Location, dtype: bool

In [142]:
df_filtered = df[loc_filter]
df_filtered

    eno    ename  salary  deptno         doj       Location
1     2     Amar    1000      10  22/03/2017      Bangalore
2     8    Sagar    1000      20  30/11/2020     California
3     4   Thomas    1000      10  18/08/2019     California
4     5     Jade    2000      10  10/02/2021         London
5     6    Smith    1000      10  01/12/2016         London
6     7   Robert    3000      20  25/06/2023          Paris
7     3     Nick    1000      30  15/09/2015          Paris
8     9    Naman    4000      30  20/01/2020          Abuja
9     1    Vikas    1000      30  03/10/2017  Port Harcourt
10   11   Dennis   41000      30  05/01/2024            NaN
11   12    Karan    2200      20  16/06/2018            NaN
12   13   Simran    1500      10  19/12/2019            NaN
13   14     Amit    2000      30  09/04/2022            NaN
14   15     Neha    1700      20  22/07/2021            NaN
15   16    Rahul    1200      10  28/03/2016            NaN
16   17    Divya    3000      30  11/11/2015            NaN
29   30   Suresh    1100      10  09/09/2018         London
30   31     Rani    1900      20  03/11/2022         London
31   32     Ajay    2100      10  26/06/2020         London
32   33    Nidhi    2400      30  12/05/2016         London
33   34    Vivek    2000      20  31/07/2017         London
34   35    Seema    3000      10  15/10/2021         London
35   36     Ritu    3200      20  01/05/2023         London
36   37    Kunal    2800      30  22/08/2015         London
37   38     Alok    2700      10  02/03/2019         London
38   39   Poonam    2600      20  05/02/2022         London
39   40     Yash    2500      30  19/07/2020         London
40   41     Nina    2300      20  28/12/2018         London
41   42    Tarun    2200      10  09/01/2021            NaN
42   43    Geeta    2100      30  14/11/2017            NaN
43   44    Ashok    1900      10  08/06/2016            NaN
44   45  Sanjana    1800      20  17/03/2023            NaN
45   46    Manoj    1700      30  24/07/2019          Lagos
46   47    Payal    1600      20  10/10/2015          Lagos

In [143]:
df_agg = df_filtered.groupby('deptno')['salary'].sum()
df_agg

deptno
10    20700
20    23300
30    63500
Name: salary, dtype: int64

In [147]:
df_agg1 = df_agg.reset_index()
df_agg1

   index  deptno  salary
0      0      10   20700
1      1      20   23300
2      2      30   63500

In [149]:
df_agg1['salary'] > 50000

0    False
1    False
2     True
Name: salary, dtype: bool

In [150]:
# way 1
having_filter = df_agg1['salary'] > 50000
df_agg1[having_filter]

   index  deptno  salary
2      2      30   63500

In [152]:
# Way 2 - Using lambda
lambda_fil = df_agg.apply(lambda x : x > 50000)
df_agg[lambda_fil].reset_index()

   index  deptno   salary
0      0     NaN      NaN
1      1     NaN      NaN
2      2     NaN  63500.0

Merge Function

In [162]:
df1 = pd.read_csv('emp1.csv')

In [161]:
df1

         Location         country
0       Bangalore           India
1       Bangalore           India
2      California             USA
3      California             USA
4          London  United Kingdom
5          London  United Kingdom
6           Paris          France
7           Paris          France
8           Abuja         Nigeria
9   Port Harcourt         Nigeria
10          Lagos         Nigeria

In [158]:
data = df.merge(df1,on='Location',how='right')

In [160]:
data.head()

   eno   ename  salary  deptno         doj    Location country
0    2    Amar    1000      10  22/03/2017   Bangalore   India
1    2    Amar    1000      10  22/03/2017   Bangalore   India
2    8   Sagar    1000      20  30/11/2020  California     USA
3    4  Thomas    1000      10  18/08/2019  California     USA
4    8   Sagar    1000      20  30/11/2020  California     USA

In [156]:
data1 = df.merge(df1,on='Location',how='inner')

In [154]:
data1.head()

   eno  ename  salary  deptno         doj    Location country
0   10  Amber    1000      10  14/05/2018   Bangalore   India
1   10  Amber    1000      10  14/05/2018   Bangalore   India
2    2   Amar    1000      10  22/03/2017   Bangalore   India
3    2   Amar    1000      10  22/03/2017   Bangalore   India
4    8  Sagar    1000      20  30/11/2020  California     USA

In [163]:
data = df.merge(df1,on='Location',how='right')