In [71]:
import pandas as pd
from openpyxl.styles.builtins import title
from pandas.core.missing import check_value_size

In [72]:
df = pd.read_csv('emp.csv')

In [73]:
df.head()

   eno   ename  salary  deptno         doj
0   10   Amber    1000      10  2018-05-14
1    2    Amar    1000      10  2017-03-22
2    8   Sagar    1000      20  2020-11-30
3    4  Thomas    1000      10  2019-08-18
4    5    Jade    2000      10  2021-02-10

In [ ]:
#specify which columns to read
df = pd.read_csv("emp.csv", usecols=["eno", "ename", "salary"])

In [ ]:
df

In [ ]:
# specfying on ly on colunms
df["ename"]

In [ ]:
# Specify a primary key (eno)
df = pd.read_csv("emp.csv", usecols=["eno", "ename", "salary"], index_col="eno")

In [ ]:
df

In [ ]:
# Return record with eno = 8
df.iloc[8]

In [ ]:
# Return record with emp # 8 and 10
df.iloc[[8,10]]

In [ ]:
df.loc[[8,10]]

In [ ]:
df.head()

In [ ]:
df.loc[[2,8]]

In [ ]:
df.iloc[[2,8]]

In [ ]:
# Get specific colunms and rows
df[["salary","ename"]].iloc[[2,8]]

In [ ]:
# Get specific range of rows
df[["salary","ename"]].iloc[2:8]

In [ ]:
# Return range of rows while jumping by 2 - it is like slicing
df[["salary","ename"]].iloc[2:8:2]

In [ ]:
df.dtypes

In [ ]:
# Specify data types of the colunm
df= pd.read_csv("emp.csv",dtype={"salary":float})

In [ ]:
df.head()

In [ ]:
df = pd.read_csv("netflix_dataset.csv")

In [ ]:
df

In [ ]:
df.count()

In [ ]:
# Read teh dat in chunk (chunk size)
for chunk in pd.read_csv("netflix_dataset.csv",chunksize=1000):
    print(chunk.head())

In [ ]:
# show few colunms
for chunk in pd.read_csv("netflix_dataset.csv",usecols=["show_id","title"],chunksize=1000):
    print(chunk.head(10))

In [ ]:
#Using iterator
iterator =  pd.read_csv("netflix_dataset.csv",usecols=["show_id","title"],chunksize=1000,iterator=True)
for chunk in iterator:
    print(chunk.head(10))

In [ ]:
df = pd.read_csv('emp.csv')

In [ ]:
df.head(20)

In [ ]:
# use iloc t read the data from row 10 to row 20
# way 1
df.iloc[9:20]

In [ ]:
# way 2 - Create a datafrae with rows 10 to 21
df = pd.read_csv("emp.csv",skiprows=10,nrows=11,header=None)

In [ ]:
df

In [ ]:
# Create a dataframe with names
df = pd.read_csv("emp.csv",skiprows=10,nrows=11,names=['empid','ename','sal','deptno','hiringdate'])

In [ ]:
df

In [ ]:
# It is not considering any header
df = pd.read_csv('emp.csv',header=0)

In [ ]:
df

In [ ]:
# using second  row a header
df = pd.read_csv('emp.csv',header=1)
df

In [ ]:
# starting from the fourth row
df = pd.read_csv('emp.csv',header=4)
df.head()

In [ ]:
# Check data type
df = pd.read_csv('emp.csv')
df.dtypes

In [ ]:
#the the dtype of date to date_time
df = pd.read_csv('emp.csv',parse_dates=['doj'])
df.dtypes

In [ ]:
df['doj'].head()

In [ ]:
df['doj'].dt.year.head()

In [ ]:
df['doj'].dt.month.head()

In [ ]:
df['doj'].dt.day.head()

In [102]:
# Filtering (using where clause in SQL)
# get all emplyee that belong to dept 10 and 20 where salary >3000
df = pd.read_csv('emp.csv')
filter1 = df['deptno']==30
filter2 = df['salary']>3000
filter3 = df['deptno']=20

In [ ]:
df[filter1&filter2]

In [83]:
df[filter1|filter3].head()

   eno   ename  salary  deptno         doj
0   10   Amber    1000      20  2018-05-14
1    2    Amar    1000      20  2017-03-22
2    8   Sagar    1000      20  2020-11-30
3    4  Thomas    1000      20  2019-08-18
4    5    Jade    2000      20  2021-02-10

In [86]:
#  Get me all the employees who do not belongs to deptno 10
# SQL : select * from emp where dept_no !=10
filter4 =df['deptno']==10

In [94]:
filter5 = ~filter4

In [95]:
df[filter5].head()

   eno   ename  salary  deptno         doj
0   10   Amber    1000      20  2018-05-14
1    2    Amar    1000      20  2017-03-22
2    8   Sagar    1000      20  2020-11-30
3    4  Thomas    1000      20  2019-08-18
4    5    Jade    2000      20  2021-02-10

In [103]:
# Sorting - we can sort by index or sort by value
df.sort_values(by='salary',ascending=False).head()

    eno   ename  salary  deptno         doj
10   11  Dennis   41000      20  2024-01-05
8     9   Naman    4000      20  2020-01-20
35   36    Ritu    3200      20  2023-05-01
16   17   Divya    3000      20  2015-11-11
34   35   Seema    3000      20  2021-10-15

In [105]:
# Multiple-column sorting
df.sort_values(by=['deptno','salary'],ascending=False).head()

    eno   ename  salary  deptno         doj
10   11  Dennis   41000      20  2024-01-05
8     9   Naman    4000      20  2020-01-20
35   36    Ritu    3200      20  2023-05-01
6     7  Robert    3000      20  2023-06-25
16   17   Divya    3000      20  2015-11-11

In [ ]:
df = pd.read_csv('emp.csv')

In [108]:
# inplace=True → modify original DataFrame
sorted = df.sort_values(by=['deptno','salary'],ascending=[True,False],inplace=True)

In [110]:
df[sorted].head()

    deptno         doj   ename  eno  salary
10      20  2024-01-05  Dennis   11   41000
8       20  2020-01-20   Naman    9    4000
35      20  2023-05-01    Ritu   36    3200
6       20  2023-06-25  Robert    7    3000
16      20  2015-11-11   Divya   17    3000

In [112]:
# Sort by Index
df.sort_index().head()

   eno   ename  salary  deptno         doj
0   10   Amber    1000      20  2018-05-14
1    2    Amar    1000      20  2017-03-22
2    8   Sagar    1000      20  2020-11-30
3    4  Thomas    1000      20  2019-08-18
4    5    Jade    2000      20  2021-02-10