In [4]:
import pandas as pd

In [6]:
pd.read_csv("emp.csv")

    eno    ename  salary  deptno         doj
0    10    Amber    1000      10  2018-05-14
1     2     Amar    1000      10  2017-03-22
2     8    Sagar    1000      20  2020-11-30
3     4   Thomas    1000      10  2019-08-18
4     5     Jade    2000      10  2021-02-10
5     6    Smith    1000      10  2016-12-01
6     7   Robert    3000      20  2023-06-25
7     3     Nick    1000      30  2015-09-15
8     9    Naman    4000      30  2020-01-20
9     1    Vikas    1000      30  2017-10-03
10   11   Dennis   41000      30  2024-01-05
11   12    Karan    2200      20  2018-06-16
12   13   Simran    1500      10  2019-12-19
13   14     Amit    2000      30  2022-04-09
14   15     Neha    1700      20  2021-07-22
15   16    Rahul    1200      10  2016-03-28
16   17    Divya    3000      30  2015-11-11
17   18   Rakesh    1800      10  2020-09-04
18   19   Monica    2500      20  2023-08-07
19   20     John    2300      30  2018-10-29
20   21    Sneha    2700      10  2022-12-14
21   22    David    1000      20  2017-02-17
22   23    Anita    1500      30  2019-05-21
23   24    Vinod    1800      10  2016-07-30
24   25    Meena    2000      20  2020-03-13
25   26    Harsh    1600      10  2021-09-25
26   27   Kavita    1400      30  2019-01-06
27   28    Mohan    1300      10  2015-04-17
28   29    Priya    1200      20  2023-02-11
29   30   Suresh    1100      10  2018-09-09
30   31     Rani    1900      20  2022-11-03
31   32     Ajay    2100      10  2020-06-26
32   33    Nidhi    2400      30  2016-05-12
33   34    Vivek    2000      20  2017-07-31
34   35    Seema    3000      10  2021-10-15
35   36     Ritu    3200      20  2023-05-01
36   37    Kunal    2800      30  2015-08-22
37   38     Alok    2700      10  2019-03-02
38   39   Poonam    2600      20  2022-02-05
39   40     Yash    2500      30  2020-07-19
40   41     Nina    2300      20  2018-12-28
41   42    Tarun    2200      10  2021-01-09
42   43    Geeta    2100      30  2017-11-14
43   44    Ashok    1900      10  2016-06-08
44   45  Sanjana    1800      20  2023-03-17
45   46    Manoj    1700      30  2019-07-24
46   47    Payal    1600      20  2015-10-10

In [3]:

Pandas => Open source library for data manipulation and analysis. It has 2 main data structures:
    1) Dataframe => 2 D labelled data strcuture ( rows and colums). Labelled on columns with column name and rows with indexes
    
    2) Series => 1 D labelled array(List)


8:11

SyntaxError: unmatched ')' (782201624.py, line 2)

In [7]:
df = pd.read_csv("emp.csv")

In [8]:
df.dtypes

eno        int64
ename     object
salary     int64
deptno     int64
doj       object
dtype: object

In [9]:
type(df)

pandas.core.frame.DataFrame

In [10]:
df.head(10)

   eno   ename  salary  deptno         doj
0   10   Amber    1000      10  2018-05-14
1    2    Amar    1000      10  2017-03-22
2    8   Sagar    1000      20  2020-11-30
3    4  Thomas    1000      10  2019-08-18
4    5    Jade    2000      10  2021-02-10
5    6   Smith    1000      10  2016-12-01
6    7  Robert    3000      20  2023-06-25
7    3    Nick    1000      30  2015-09-15
8    9   Naman    4000      30  2020-01-20
9    1   Vikas    1000      30  2017-10-03

In [11]:
ser = df['ename']

In [12]:
type(ser)

pandas.core.series.Series

In [13]:
cols = ['ename',"salary"]

In [16]:
unknown_ds = df[cols]

In [15]:
type(unknown_ds)

pandas.core.frame.DataFrame

In [17]:
ls  = [1,2,3]

In [27]:
type(ls)

list

In [18]:
# select eno,ename,salary from emp

col = ['eno','ename','salary']

df[col]

# select * from emp
#df

    eno    ename  salary
0    10    Amber    1000
1     2     Amar    1000
2     8    Sagar    1000
3     4   Thomas    1000
4     5     Jade    2000
5     6    Smith    1000
6     7   Robert    3000
7     3     Nick    1000
8     9    Naman    4000
9     1    Vikas    1000
10   11   Dennis   41000
11   12    Karan    2200
12   13   Simran    1500
13   14     Amit    2000
14   15     Neha    1700
15   16    Rahul    1200
16   17    Divya    3000
17   18   Rakesh    1800
18   19   Monica    2500
19   20     John    2300
20   21    Sneha    2700
21   22    David    1000
22   23    Anita    1500
23   24    Vinod    1800
24   25    Meena    2000
25   26    Harsh    1600
26   27   Kavita    1400
27   28    Mohan    1300
28   29    Priya    1200
29   30   Suresh    1100
30   31     Rani    1900
31   32     Ajay    2100
32   33    Nidhi    2400
33   34    Vivek    2000
34   35    Seema    3000
35   36     Ritu    3200
36   37    Kunal    2800
37   38     Alok    2700
38   39   Poonam    2600
39   40     Yash    2500
40   41     Nina    2300
41   42    Tarun    2200
42   43    Geeta    2100
43   44    Ashok    1900
44   45  Sanjana    1800
45   46    Manoj    1700
46   47    Payal    1600