In [1]:
import pandas as pd

In [7]:
df_emp = pd.read_csv('data/employees.csv')

In [8]:
df_emp

   eno   ename  deptno
0    1    Ajay      10
1    2   Vijay      20
2    3  Mahesh      30
3    4  Thomas      40
4    5  Robert      50

In [10]:
df_dept = pd.read_csv('data/department.csv')

In [11]:
df_dept

   deptid deptname
0      30   Travel
1      80    Forex
2      10  Finance
3      20       IT

In [29]:
df_sal = pd.read_csv('data/salary.csv')

In [30]:
df_sal

   eno  salary
0    1    1000
1    2    3000
2    3    2000

Inner Join

In [13]:
# SQL = slect * from employee as emp inner join departmen as dept on emp.deptno = dept.deptid
df_emp.merge(df_dept,left_on='deptno',right_on='deptid', how='inner')

   eno   ename  deptno  deptid deptname
0    1    Ajay      10      10  Finance
1    2   Vijay      20      20       IT
2    3  Mahesh      30      30   Travel

In [15]:
# SQL = slect * from employee as emp left join departmen as dept on emp.deptno = dept.deptid
df_emp.merge(df_dept,left_on='deptno',right_on='deptid', how='left')

   eno   ename  deptno  deptid deptname
0    1    Ajay      10    10.0  Finance
1    2   Vijay      20    20.0       IT
2    3  Mahesh      30    30.0   Travel
3    4  Thomas      40     NaN      NaN
4    5  Robert      50     NaN      NaN

In [16]:
# SQL = select * from employee as emp right join departmen as dept on emp.deptno = dept.deptid
df_emp.merge(df_dept,left_on='deptno',right_on='deptid', how='right')

   eno   ename  deptno  deptid deptname
0  3.0  Mahesh    30.0      30   Travel
1  NaN     NaN     NaN      80    Forex
2  1.0    Ajay    10.0      10  Finance
3  2.0   Vijay    20.0      20       IT

In [17]:
# This can be achieved by using the left join and changing the dataframe sequence
df_dept.merge(df_emp,left_on='deptid',right_on='deptno', how='left')

   deptid deptname  eno   ename  deptno
0      30   Travel  3.0  Mahesh    30.0
1      80    Forex  NaN     NaN     NaN
2      10  Finance  1.0    Ajay    10.0
3      20       IT  2.0   Vijay    20.0

In [19]:
# full join
df_outer = df_emp.merge(df_dept,left_on='deptno',right_on='deptid', how='outer')

In [20]:
df_outer

   eno   ename  deptno  deptid deptname
0  1.0    Ajay    10.0    10.0  Finance
1  2.0   Vijay    20.0    20.0       IT
2  3.0  Mahesh    30.0    30.0   Travel
3  4.0  Thomas    40.0     NaN      NaN
4  5.0  Robert    50.0     NaN      NaN
5  NaN     NaN     NaN    80.0    Forex

# Concat

In [23]:
pd.concat([df_emp,df_dept],axis=0)

   eno   ename  deptno  deptid deptname
0  1.0    Ajay    10.0     NaN      NaN
1  2.0   Vijay    20.0     NaN      NaN
2  3.0  Mahesh    30.0     NaN      NaN
3  4.0  Thomas    40.0     NaN      NaN
4  5.0  Robert    50.0     NaN      NaN
0  NaN     NaN     NaN    30.0   Travel
1  NaN     NaN     NaN    80.0    Forex
2  NaN     NaN     NaN    10.0  Finance
3  NaN     NaN     NaN    20.0       IT

In [28]:
pd.concat([df_emp,df_dept],axis=1)

   eno   ename  deptno  deptid deptname
0    1    Ajay      10    30.0   Travel
1    2   Vijay      20    80.0    Forex
2    3  Mahesh      30    10.0  Finance
3    4  Thomas      40    20.0       IT
4    5  Robert      50     NaN      NaN

In [26]:
# Change the sequence
pd.concat([df_dept,df_emp],axis=1)

   deptid deptname  eno   ename  deptno
0    30.0   Travel    1    Ajay      10
1    80.0    Forex    2   Vijay      20
2    10.0  Finance    3  Mahesh      30
3    20.0       IT    4  Thomas      40
4     NaN      NaN    5  Robert      50

In [32]:
# combine three dataframes
pd.concat([df_emp,df_dept,df_sal],axis=1)

   eno   ename  deptno  deptid deptname  eno  salary
0    1    Ajay      10    30.0   Travel  1.0  1000.0
1    2   Vijay      20    80.0    Forex  2.0  3000.0
2    3  Mahesh      30    10.0  Finance  3.0  2000.0
3    4  Thomas      40    20.0       IT  NaN     NaN
4    5  Robert      50     NaN      NaN  NaN     NaN

In [33]:
pd.concat([df_emp,df_dept,df_sal],axis=0)

   eno   ename  deptno  deptid deptname  salary
0  1.0    Ajay    10.0     NaN      NaN     NaN
1  2.0   Vijay    20.0     NaN      NaN     NaN
2  3.0  Mahesh    30.0     NaN      NaN     NaN
3  4.0  Thomas    40.0     NaN      NaN     NaN
4  5.0  Robert    50.0     NaN      NaN     NaN
0  NaN     NaN     NaN    30.0   Travel     NaN
1  NaN     NaN     NaN    80.0    Forex     NaN
2  NaN     NaN     NaN    10.0  Finance     NaN
3  NaN     NaN     NaN    20.0       IT     NaN
0  1.0     NaN     NaN     NaN      NaN  1000.0
1  2.0     NaN     NaN     NaN      NaN  3000.0
2  3.0     NaN     NaN     NaN      NaN  2000.0

In [35]:
# Using join and concat
pd.concat([df_emp,df_dept], axis=1,join='inner')

   eno   ename  deptno  deptid deptname
0    1    Ajay      10      30   Travel
1    2   Vijay      20      80    Forex
2    3  Mahesh      30      10  Finance
3    4  Thomas      40      20       IT

In [36]:
df_emp1 = pd.read_csv('data/employees1.csv')

In [37]:
df_emp1

   eno   ename  deptno
0    1    Ajay      10
1    2   Vijay      20
2    3  Mahesh      30
3   40  Rakesh      70
4   50  Sanjay      60

In [38]:
pd.concat([df_emp,df_emp1])

   eno   ename  deptno
0    1    Ajay      10
1    2   Vijay      20
2    3  Mahesh      30
3    4  Thomas      40
4    5  Robert      50
0    1    Ajay      10
1    2   Vijay      20
2    3  Mahesh      30
3   40  Rakesh      70
4   50  Sanjay      60

In [39]:
pd.concat([df_emp1,df_emp1]).drop_duplicates()

   eno   ename  deptno
0    1    Ajay      10
1    2   Vijay      20
2    3  Mahesh      30
3   40  Rakesh      70
4   50  Sanjay      60

# Intersection

In [40]:
df_emp.merge(df_emp1,how='inner')

   eno   ename  deptno
0    1    Ajay      10
1    2   Vijay      20
2    3  Mahesh      30

# Write file to parquet

In [41]:
df_net = pd.read_csv('netflix_dataset.csv')

In [43]:
df_net.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [44]:
df_net.to_parquet('data/netflix.parquet')

In [45]:
df_prq = pd.read_parquet('data/netflix.parquet')

In [46]:
df_prq.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,None,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,None,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",None,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,None,None,None,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,None,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [47]:
df_prq.to_json('data/netflix.json')